version: "3.9"
services:
  backend-api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    image: sympnet-api:latest
    ports:
      - "5057:8080"
    environment:
      ConnectionStrings__DefaultConnection: >
        Host=db;Database=sympnetdb;
        Username=postgres;Password=securepass
    depends_on:
      - db
    networks:
      - sympnet-network

  dashboard:
    build: 
      context: .
      dockerfile: Dockerfile.dashboard
    image: sympnet-dashboard:latest
    ports:
      - "5002:8080"
    environment:
      ApiSettings__BaseUrl: "http://backend-api:8080"
    depends_on:
      - backend-api
    networks:
      - sympnet-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB:       sympnetdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sympnet-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - sympnet-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - sympnet-network

volumes:
  pgdata:
networks:
  sympnet-network:
    driver: bridge
