FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY SympNet.WebApi/SympNet.WebApi.csproj SympNet.WebApi/
RUN dotnet restore SympNet.WebApi/SympNet.WebApi.csproj
COPY . .
WORKDIR /src/SympNet.WebApi
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "SympNet.WebApi.dll"]
