CREATE TABLE "Conversations" (
    "Id" uuid NOT NULL,
    "DoctorId" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastMessageAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id")
);


CREATE TABLE "DoctorNotifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DoctorUserId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "AppointmentId" integer NOT NULL,
    "IsUrgent" boolean NOT NULL,
    "IsRead" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DoctorNotifications" PRIMARY KEY ("Id")
);


CREATE TABLE "PatientNotifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientUserId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "AppointmentId" integer NOT NULL,
    "Status" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PatientNotifications" PRIMARY KEY ("Id")
);


CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "FullName" text,
    "Speciality" text,
    "Latitude" double precision,
    "Longitude" double precision,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLoginAt" timestamp with time zone,
    "PhotoUrl" text,
    "ResetToken" text,
    "ResetTokenExpiry" timestamp with time zone,
    "IsEmailVerified" boolean NOT NULL,
    "VerificationCode" text,
    "VerificationCodeExpiry" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);


CREATE TABLE "VideoCallSessions" (
    "Id" uuid NOT NULL,
    "ConversationId" uuid NOT NULL,
    "InitiatorId" uuid NOT NULL,
    "ReceiverId" uuid NOT NULL,
    "Status" text NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "EndedAt" timestamp with time zone,
    "DurationSeconds" integer,
    CONSTRAINT "PK_VideoCallSessions" PRIMARY KEY ("Id")
);


CREATE TABLE "ChatMessages" (
    "Id" uuid NOT NULL,
    "ConversationId" uuid NOT NULL,
    "SenderId" uuid NOT NULL,
    "SenderRole" text NOT NULL,
    "Content" text NOT NULL,
    "MessageType" text NOT NULL,
    "FileUrl" text,
    "IsRead" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatMessages_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Consultations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientName" text NOT NULL,
    "PatientEmail" text NOT NULL,
    "Symptoms" text NOT NULL,
    "Diagnosis" text NOT NULL,
    "Recommendations" text NOT NULL,
    "ConfidenceScore" double precision NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "DoctorId" uuid NOT NULL,
    CONSTRAINT "PK_Consultations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Consultations_Users_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Doctors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Speciality" text NOT NULL,
    "LicenseNumber" text NOT NULL,
    "Address" text NOT NULL,
    "Latitude" double precision,
    "Longitude" double precision,
    "CreatedAt" timestamp with time zone NOT NULL,
    "TotalConsultations" integer NOT NULL,
    "TotalPatients" integer NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Doctors_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Message" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" uuid NOT NULL,
    "ReceiverId" uuid NOT NULL,
    "Content" character varying(5000) NOT NULL,
    "AttachmentUrl" text,
    "AttachmentType" text,
    "AttachmentName" text,
    "AttachmentSize" bigint,
    "IsRead" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "IsDeletedForSender" boolean NOT NULL,
    "IsDeletedForReceiver" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Message" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Message_Users_ReceiverId" FOREIGN KEY ("ReceiverId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Message_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Patients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "Gender" text NOT NULL,
    "Address" text NOT NULL,
    "BloodType" text NOT NULL,
    "Allergies" text NOT NULL,
    "MedicalHistory" text NOT NULL,
    "ConsultationCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Patients_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Appointments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" uuid NOT NULL,
    "DoctorId" integer NOT NULL,
    "DateTime" timestamp with time zone NOT NULL,
    "Duration" integer NOT NULL,
    "Status" text NOT NULL,
    "Type" text,
    "Notes" text,
    "Reason" text,
    "IsUrgent" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ReminderSentAt" timestamp with time zone,
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Appointments_Users_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "BlockedSlots" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DoctorId" integer NOT NULL,
    "StartDateTime" timestamp with time zone NOT NULL,
    "EndDateTime" timestamp with time zone NOT NULL,
    "Reason" text NOT NULL,
    "IsRecurring" boolean NOT NULL,
    "RecurrencePattern" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BlockedSlots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BlockedSlots_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE
);


CREATE TABLE "WorkingHours" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DoctorId" integer NOT NULL,
    "DayOfWeek" integer NOT NULL,
    "StartTime" time without time zone NOT NULL,
    "EndTime" time without time zone NOT NULL,
    "SlotDuration" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_WorkingHours" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkingHours_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Ordonnances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrdonnanceCode" text NOT NULL,
    "PatientId" integer NOT NULL,
    "DoctorId" integer NOT NULL,
    "ConsultationId" integer,
    "Diagnosis" text NOT NULL,
    "MedicationsJson" text NOT NULL,
    "Notes" text,
    "Status" integer NOT NULL,
    "HasAIAlerts" boolean NOT NULL,
    "AIAlertsJson" text,
    "DoctorConfirmed" boolean NOT NULL,
    "ConfirmedAt" timestamp with time zone,
    "PdfPath" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Ordonnances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Ordonnances_Consultations_ConsultationId" FOREIGN KEY ("ConsultationId") REFERENCES "Consultations" ("Id"),
    CONSTRAINT "FK_Ordonnances_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Ordonnances_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_Appointments_DoctorId" ON "Appointments" ("DoctorId");


CREATE INDEX "IX_Appointments_PatientId" ON "Appointments" ("PatientId");


CREATE INDEX "IX_BlockedSlots_DoctorId" ON "BlockedSlots" ("DoctorId");


CREATE INDEX "IX_ChatMessages_ConversationId" ON "ChatMessages" ("ConversationId");


CREATE INDEX "IX_Consultations_DoctorId" ON "Consultations" ("DoctorId");


CREATE INDEX "IX_Doctors_UserId" ON "Doctors" ("UserId");


CREATE INDEX "IX_Message_ReceiverId" ON "Message" ("ReceiverId");


CREATE INDEX "IX_Message_SenderId_ReceiverId_SentAt" ON "Message" ("SenderId", "ReceiverId", "SentAt");


CREATE INDEX "IX_Ordonnances_ConsultationId" ON "Ordonnances" ("ConsultationId");


CREATE INDEX "IX_Ordonnances_DoctorId" ON "Ordonnances" ("DoctorId");


CREATE INDEX "IX_Ordonnances_PatientId" ON "Ordonnances" ("PatientId");


CREATE INDEX "IX_Patients_UserId" ON "Patients" ("UserId");


CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");


CREATE INDEX "IX_WorkingHours_DoctorId" ON "WorkingHours" ("DoctorId");


