using System.Security.Claims;
using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using SympNet.WebApi.Data;
using SympNet.WebApi.Hubs;
using SympNet.WebApi.Services;

var builder = WebApplication.CreateBuilder(args);

builder.Configuration.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddSignalR();
builder.Services.AddHttpClient();
builder.Services.AddSingleton<Microsoft.AspNetCore.SignalR.IUserIdProvider, NameUserIdProvider>();




builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("Default")));

var jwtKey = builder.Configuration["Jwt:Key"] ?? "SympNet_Super_Secret_Key_2026_TEKup_Very_Long_For_256bits_Minimum!";

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer           = false,
            ValidateAudience         = false,
            ValidateLifetime         = true,
            ValidateIssuerSigningKey = true,
            IssuerSigningKey         = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey))
        };

        options.Events = new JwtBearerEvents
        {
            OnMessageReceived = context =>
            {
                var accessToken = context.Request.Query["access_token"];
                var path = context.HttpContext.Request.Path;
                
                if (path.StartsWithSegments("/hubs"))
                {
                    var hasHeader = context.Request.Headers.ContainsKey("Authorization");
                    Console.WriteLine($"[SignalR-Auth] Connection attempt to {path}. Token in query: {!string.IsNullOrEmpty(accessToken)}, Token in header: {hasHeader}");
                    if (!string.IsNullOrEmpty(accessToken))
                    {
                        context.Token = accessToken;
                    }
                }
                return Task.CompletedTask;
            }
        };
    });

builder.Services.AddScoped<JwtService>();
builder.Services.AddScoped<EmailService>();
builder.Services.AddSignalR();
builder.Services.AddHttpContextAccessor();

//  Enregistrement du service IA 
builder.Services.AddHttpClient<IAIService, AIService>(client =>
{
    var aiUrl = builder.Configuration["AIService:Url"] ?? "http://localhost:8001";
    client.BaseAddress = new Uri(aiUrl);
    client.Timeout = TimeSpan.FromMinutes(3);
});

// AllowCredentials() requis par SignalR
builder.Services.AddCors(options =>
{
    options.AddPolicy("SignalRPolicy", policy =>
        policy
            .SetIsOriginAllowed(_ => true) // autoriser toutes les origines en développement
            .AllowAnyHeader()
            .AllowAnyMethod()
            .AllowCredentials()); //   WebSocket
});

var app = builder.Build();

// Seed admin
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    var adminEmail    = builder.Configuration["Admin:Email"]    ?? "admin@sympnet.com";
    var adminPassword = builder.Configuration["Admin:Password"] ?? "Admin123!";

    db.Database.EnsureCreated();
    try
    {
        db.Database.ExecuteSqlRaw(@"
CREATE TABLE IF NOT EXISTS ""DoctorNotifications"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""DoctorUserId"" uuid NOT NULL,
    ""Title"" text NOT NULL,
    ""Message"" text NOT NULL,
    ""AppointmentId"" integer NOT NULL,
    ""IsUrgent"" boolean NOT NULL,
    ""IsRead"" boolean NOT NULL,
    ""SentAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_DoctorNotifications"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""PatientNotifications"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""PatientUserId"" uuid NOT NULL,
    ""Title"" text NOT NULL,
    ""Message"" text NOT NULL,
    ""IsUrgent"" boolean NOT NULL,
    ""IsRead"" boolean NOT NULL,
    ""SentAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_PatientNotifications"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""BlogPosts"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""Title"" text NOT NULL,
    ""Content"" text NOT NULL,
    ""Summary"" text NOT NULL,
    ""ImageUrl"" text NOT NULL,
    ""Category"" text NOT NULL,
    ""AuthorId"" uuid NOT NULL,
    ""AuthorName"" text NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""UpdatedAt"" timestamp with time zone NOT NULL,
    ""ReadingTime"" integer NOT NULL,
    ""IsPublished"" boolean NOT NULL,
    ""Views"" integer NOT NULL,
    CONSTRAINT ""PK_BlogPosts"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""Ordonnances"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""OrdonnanceCode"" text NOT NULL,
    ""PatientId"" integer NOT NULL,
    ""DoctorId"" integer NOT NULL,
    ""ConsultationId"" integer,
    ""Diagnosis"" text NOT NULL,
    ""MedicationsJson"" text NOT NULL,
    ""Notes"" text,
    ""Status"" integer NOT NULL,
    ""HasAIAlerts"" boolean NOT NULL,
    ""AIAlertsJson"" text,
    ""DoctorConfirmed"" boolean NOT NULL,
    ""ConfirmedAt"" timestamp with time zone,
    ""PdfPath"" text,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_Ordonnances"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""Notifications"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""UserId"" uuid NOT NULL,
    ""Title"" text NOT NULL,
    ""Message"" text NOT NULL,
    ""Type"" integer NOT NULL,
    ""ActionUrl"" text,
    ""IsRead"" boolean NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_Notifications"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""ContactMessages"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""FirstName"" text NOT NULL,
    ""LastName"" text NOT NULL,
    ""Email"" text NOT NULL,
    ""Phone"" text,
    ""Topic"" text NOT NULL,
    ""Message"" text NOT NULL,
    ""SentAt"" timestamp with time zone NOT NULL,
    ""IsRead"" boolean NOT NULL,
    CONSTRAINT ""PK_ContactMessages"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""NewsletterSubscribers"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""Email"" text NOT NULL,
    ""SubscribedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_NewsletterSubscribers"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""DoctorRatings"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""DoctorId"" integer NOT NULL,
    ""PatientId"" integer NOT NULL,
    ""Score"" integer NOT NULL,
    ""Comment"" text,
    ""IsModerated"" boolean NOT NULL DEFAULT false,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_DoctorRatings"" PRIMARY KEY (""Id"")
);
ALTER TABLE ""Doctors"" ADD COLUMN IF NOT EXISTS ""Bio"" text;
ALTER TABLE ""Doctors"" ADD COLUMN IF NOT EXISTS ""GraduationYear"" integer;

ALTER TABLE ""Patients"" ADD COLUMN IF NOT EXISTS ""BloodType"" text DEFAULT '';
ALTER TABLE ""Patients"" ADD COLUMN IF NOT EXISTS ""Allergies"" text DEFAULT '';
ALTER TABLE ""Patients"" ADD COLUMN IF NOT EXISTS ""MedicalHistory"" text DEFAULT '';
ALTER TABLE ""Patients"" ADD COLUMN IF NOT EXISTS ""ChronicDiseases"" text DEFAULT '';
ALTER TABLE ""Patients"" ADD COLUMN IF NOT EXISTS ""CurrentMedications"" text DEFAULT '';
ALTER TABLE ""Doctors"" ADD COLUMN IF NOT EXISTS ""PhoneNumber"" text;
");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error creating tables: {ex.Message}");
    }

    if (!db.Users.Any(u => u.Role == "Admin"))
    {
        db.Users.Add(new SympNet.WebApi.Models.User
        {
            Id           = Guid.NewGuid(),
            Email        = adminEmail,
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(adminPassword),
            Role         = "Admin",
            IsActive     = true,
            FullName     = "Super Administrateur",
            CreatedAt    = DateTime.UtcNow
        });
        db.SaveChanges();
        Console.WriteLine($" ADMIN CRÉÉ — Email: {adminEmail}");
    }
    else
    {
        Console.WriteLine(" L'administrateur existe déjà.");
    }

    if (!db.DoctorRatings.Any())
    {
        var firstDoc = db.Doctors.FirstOrDefault();
        var firstPatient = db.Patients.FirstOrDefault();
        if (firstDoc != null && firstPatient != null)
        {
            db.DoctorRatings.AddRange(
                new SympNet.WebApi.Models.DoctorRating { DoctorId = firstDoc.Id, PatientId = firstPatient.Id, Score = 5, Comment = "Excellent médecin, très à l'écoute et rassurant. Je recommande vivement pour son professionnalisme.", IsModerated = true, CreatedAt = DateTime.UtcNow.AddDays(-2) },
                new SympNet.WebApi.Models.DoctorRating { DoctorId = firstDoc.Id, PatientId = firstPatient.Id, Score = 4, Comment = "Consultation rapide et efficace. Le cabinet est très propre et l'attente n'était pas longue.", IsModerated = true, CreatedAt = DateTime.UtcNow.AddDays(-5) }
            );
            db.SaveChanges();
            Console.WriteLine(" Faux avis insérés pour tester !");
        }
    }
}

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

//  CORS avant Authentication
app.UseCors("SignalRPolicy");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapHub<ChatHub>("/hubs/chat");

//  hub de notifications
app.MapHub<NotificationHub>("/hubs/notifications");

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<SympNet.WebApi.Data.AppDbContext>();
    try
    {
        db.Database.ExecuteSqlRaw("ALTER TABLE \"Appointments\" ADD COLUMN IF NOT EXISTS \"Duration\" integer NOT NULL DEFAULT 30;");
        db.Database.ExecuteSqlRaw("ALTER TABLE \"PatientNotifications\" ADD COLUMN IF NOT EXISTS \"AppointmentId\" integer NOT NULL DEFAULT 0;");
        db.Database.ExecuteSqlRaw("ALTER TABLE \"DoctorNotifications\" ADD COLUMN IF NOT EXISTS \"AppointmentId\" integer NOT NULL DEFAULT 0;");
        db.Database.ExecuteSqlRaw("ALTER TABLE \"Appointments\" ADD COLUMN IF NOT EXISTS \"IsUrgent\" boolean NOT NULL DEFAULT false;");
        db.Database.ExecuteSqlRaw("ALTER TABLE \"Appointments\" ADD COLUMN IF NOT EXISTS \"Reason\" text;");
        db.Database.ExecuteSqlRaw("ALTER TABLE \"Appointments\" ADD COLUMN IF NOT EXISTS \"Type\" text DEFAULT 'Consultation';");
        db.Database.ExecuteSqlRaw("ALTER TABLE \"Appointments\" ADD COLUMN IF NOT EXISTS \"UpdatedAt\" timestamp with time zone;");
        db.Database.ExecuteSqlRaw("ALTER TABLE \"Appointments\" ADD COLUMN IF NOT EXISTS \"ReminderSentAt\" timestamp with time zone;");
        db.Database.ExecuteSqlRaw("ALTER TABLE \"PatientNotifications\" ADD COLUMN IF NOT EXISTS \"Status\" text DEFAULT '';");
        db.Database.ExecuteSqlRaw("ALTER TABLE \"DoctorNotifications\" ADD COLUMN IF NOT EXISTS \"IsUrgent\" boolean NOT NULL DEFAULT false;");
        
        try {
            db.Database.ExecuteSqlRaw("ALTER TABLE \"WorkingHours\" ALTER COLUMN \"DoctorId\" TYPE integer USING 0;");
        } catch {
            db.Database.ExecuteSqlRaw("ALTER TABLE \"WorkingHours\" DROP COLUMN IF EXISTS \"DoctorId\";");
            db.Database.ExecuteSqlRaw("ALTER TABLE \"WorkingHours\" ADD COLUMN IF NOT EXISTS \"DoctorId\" integer NOT NULL DEFAULT 0;");
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine($"DB Patch Warning: {ex.Message}");
    }
}

app.Run();

public class NameUserIdProvider : Microsoft.AspNetCore.SignalR.IUserIdProvider
{
    public string? GetUserId(Microsoft.AspNetCore.SignalR.HubConnectionContext connection)
    {
        return connection.User?.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value 
            ?? connection.User?.FindFirst("sub")?.Value;
    }
}