using System.Security.Claims;
using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using SympNet.WebApi.Data;
using SympNet.WebApi.Hubs;
using SympNet.WebApi.Services;

var builder = WebApplication.CreateBuilder(args);

builder.Configuration.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddSignalR();


builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("Default")));

var jwtKey = builder.Configuration["Jwt:Key"] ?? "SympNet_Super_Secret_Key_2026_TEKup_Very_Long_For_256bits_Minimum!";

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer           = false,
            ValidateAudience         = false,
            ValidateLifetime         = true,
            ValidateIssuerSigningKey = true,
            IssuerSigningKey         = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey))
        };

        //  permet à SignalR de lire le token depuis la query string
        options.Events = new JwtBearerEvents
        {
            OnMessageReceived = context =>
            {
                var accessToken = context.Request.Query["access_token"];
                var path = context.HttpContext.Request.Path;
                if (!string.IsNullOrEmpty(accessToken) &&
                    path.StartsWithSegments("/hubs"))
                {
                    context.Token = accessToken;
                }
                return Task.CompletedTask;
            }
        };
    });

builder.Services.AddScoped<JwtService>();
builder.Services.AddScoped<EmailService>();
builder.Services.AddSignalR();
builder.Services.AddHttpContextAccessor();

//  Enregistrement du service IA (MS1)
builder.Services.AddHttpClient<IAIService, AIService>(client =>
{
    var aiUrl = builder.Configuration["AIService:Url"] ?? "http://localhost:8000";
    client.BaseAddress = new Uri(aiUrl);
});

// AllowCredentials() requis par SignalR
builder.Services.AddCors(options =>
{
    options.AddPolicy("SignalRPolicy", policy =>
        policy
            .WithOrigins(
                "http://localhost:5002",   // Blazor dev
                "https://localhost:5002",
                "http://127.0.0.1:5002",
                "https://127.0.0.1:5002"
            )
            .AllowAnyHeader()
            .AllowAnyMethod()
            .AllowCredentials()); //  pour WebSocket
});

var app = builder.Build();

// Seed admin
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    var adminEmail    = builder.Configuration["Admin:Email"]    ?? "admin@sympnet.com";
    var adminPassword = builder.Configuration["Admin:Password"] ?? "Admin123!";

    db.Database.EnsureCreated();
    try
    {
        db.Database.ExecuteSqlRaw(@"
CREATE TABLE IF NOT EXISTS ""DoctorNotifications"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""DoctorUserId"" uuid NOT NULL,
    ""Title"" text NOT NULL,
    ""Message"" text NOT NULL,
    ""AppointmentId"" integer NOT NULL,
    ""IsUrgent"" boolean NOT NULL,
    ""IsRead"" boolean NOT NULL,
    ""SentAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_DoctorNotifications"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""PatientNotifications"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""PatientUserId"" uuid NOT NULL,
    ""Title"" text NOT NULL,
    ""Message"" text NOT NULL,
    ""IsUrgent"" boolean NOT NULL,
    ""IsRead"" boolean NOT NULL,
    ""SentAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_PatientNotifications"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""BlogPosts"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""Title"" text NOT NULL,
    ""Content"" text NOT NULL,
    ""Summary"" text NOT NULL,
    ""ImageUrl"" text NOT NULL,
    ""Category"" text NOT NULL,
    ""AuthorId"" uuid NOT NULL,
    ""AuthorName"" text NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""UpdatedAt"" timestamp with time zone NOT NULL,
    ""ReadingTime"" integer NOT NULL,
    ""IsPublished"" boolean NOT NULL,
    ""Views"" integer NOT NULL,
    CONSTRAINT ""PK_BlogPosts"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""Ordonnances"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""OrdonnanceCode"" text NOT NULL,
    ""PatientId"" integer NOT NULL,
    ""DoctorId"" integer NOT NULL,
    ""ConsultationId"" integer,
    ""Diagnosis"" text NOT NULL,
    ""MedicationsJson"" text NOT NULL,
    ""Notes"" text,
    ""Status"" integer NOT NULL,
    ""HasAIAlerts"" boolean NOT NULL,
    ""AIAlertsJson"" text,
    ""DoctorConfirmed"" boolean NOT NULL,
    ""ConfirmedAt"" timestamp with time zone,
    ""PdfPath"" text,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_Ordonnances"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""Notifications"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""UserId"" uuid NOT NULL,
    ""Title"" text NOT NULL,
    ""Message"" text NOT NULL,
    ""Type"" integer NOT NULL,
    ""ActionUrl"" text,
    ""IsRead"" boolean NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_Notifications"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""ContactMessages"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""FirstName"" text NOT NULL,
    ""LastName"" text NOT NULL,
    ""Email"" text NOT NULL,
    ""Phone"" text,
    ""Topic"" text NOT NULL,
    ""Message"" text NOT NULL,
    ""SentAt"" timestamp with time zone NOT NULL,
    ""IsRead"" boolean NOT NULL,
    CONSTRAINT ""PK_ContactMessages"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""NewsletterSubscribers"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""Email"" text NOT NULL,
    ""SubscribedAt"" timestamp with time zone NOT NULL,
    ""IsActive"" boolean NOT NULL,
    CONSTRAINT ""PK_NewsletterSubscribers"" PRIMARY KEY (""Id"")
);
CREATE TABLE IF NOT EXISTS ""DoctorRatings"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""DoctorId"" integer NOT NULL,
    ""PatientId"" integer NOT NULL,
    ""Score"" integer NOT NULL,
    ""Comment"" text,
    ""IsModerated"" boolean NOT NULL DEFAULT false,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_DoctorRatings"" PRIMARY KEY (""Id"")
);");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error creating tables: {ex.Message}");
    }

    if (!db.Users.Any(u => u.Role == "Admin"))
    {
        db.Users.Add(new SympNet.WebApi.Models.User
        {
            Id           = Guid.NewGuid(),
            Email        = adminEmail,
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(adminPassword),
            Role         = "Admin",
            IsActive     = true,
            FullName     = "Super Administrateur",
            CreatedAt    = DateTime.UtcNow
        });
        db.SaveChanges();
        Console.WriteLine($" ADMIN CRÉÉ — Email: {adminEmail}");
    }
    else
    {
        Console.WriteLine(" L'administrateur existe déjà.");
    }
}

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

//  CORS avant Authentication
app.UseCors("SignalRPolicy");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapHub<ChatHub>("/hubs/chat");

//  hub de notifications
app.MapHub<NotificationHub>("/hubs/notifications");


app.Run();